### ISSUE TITLE
Photos App Buttons Missing

### ISSUE THREAD

**Issue by AwesomeTech10** [feren-OS/feren-theme#1]
On what I'm fairly certain is the new Feren OS theme, the default Photos app has no buttons to close or minimize, etc.

![image](https://user-images.githubusercontent.com/22264706/81970417-5d59e800-95d4-11ea-912f-a5bf008cdbe4.png)

**Comment by feren** [comment]
Confirmed - that's an issue with the way I packaged the redesigned theme VS how it was original packaged - I guess if a directory is symlinked that was once its own folder it remains its own folder rather than changing to the symlinked folder, meaning feren-dark has no assets currently. Should be easy enough to fix.

**Comment by feren** [comment]
Should be fixed now.

**Comment by AwesomeTech10** [comment]
Fixed, closing issue
