### ISSUE TITLE
[Firefox Bug] Remove transparency in dropdown menus

### ISSUE THREAD

**Issue by ShivanshMisra** [feren-OS/feren-theme#3]
When I am using firefox, the dropdown menu has this transparent when using default gtk theme, other gtk themes don't have that, of course the text is almost unreadable with that kind of transparency, so i wish that it is removed, linked image shows what it looks like
![20220311_164950](https://user-images.githubusercontent.com/87258801/157857791-6d6362ea-1cfc-4b67-83a0-3fe7f06c0a1d.jpg)

**Comment by ShivanshMisra** [comment]
Also quick mention, this transparency does not go away if I enable blur in desktop effects.

**Comment by dominichayesferen** [comment]
This is a bug with Firefox not handling the theme properly. I'd recommend just using the version of Firefox Feren OS recommends to users, being the official Mozilla Firefox Flatpak by Mozilla. You can get it here: https://flathub.org/apps/details/org.mozilla.firefox (or if you're in Feren OS, get Firefox from Web Browser Manager)

Given the fact it's a Firefox-specific issue, I'm not gonna be fixing this as Firefox was enough hell to support as-is (Firefox can barely handle themes properly if you dare go a little far from the norm of flat menus and non-square/circle titlebar buttons, and to try to support Firefox would mean seriously breaking the theme's consistency with the Feren OS Qt Applications Style, and for what when nearly every application in existence, that uses GTK+ stylesheets, works just fine with this theme). _I've got better things to spend my time on than work on making the theme support a broken program that doesn't even support themes properly._

This issue will now be closed since there's no point keeping it open given what has been said above, but anyone else is free to try their hand at fixing this issue, though preferably upstream in Firefox where the problem ultimately resides.

**Comment by dominichayesferen** [comment]
That being said, if you see this same issue on the following applications, then you've got a buggy and/or incomplete theme installation:
- Google Chrome
- Chromium
- Vivaldi
- Brave
- Microsoft Edge
- Any GNOME application that doesn't force Adwaita
- Files (Nemo)

**Comment by dominichayesferen** [comment]
Update: While Firefox still has this issue, https://github.com/dominichayesferen/Firefox-CSSTheme-GTKless fixes it.
